name : Deploy code on Lambda

on:
    push:
        branches:
            - main
jobs:
    deploy_lambda:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: setup node js
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            - name: clean old dependencies
              run: rm -rf node_modules package-lock.json

            - name: install dependencies
              run: npm install

            - name: prune dev dependencies
              run: npm prune --production

            #- name: build lambda deployment package
              #run: |
                #zip -r lambda_package.zip index.js app.js node_modules

            - name: build lambda deployment package
              run: |
                zip -r lambda_package.zip . -x "*.git*" "*.github*"

            - name: Upload Lambda package artifact
              uses: actions/upload-artifact@v4
              with:
                name: lambda_package
                path: lambda_package.zip


            - name: deploy lambda function
              uses: appleboy/lambda-action@v0.2.0
              with:
                aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws_region: ${{ secrets.AWS_REGION }}
                function_name: sample-nodejs-lambda       # your Lambda function name
                zip_file: lambda_package.zip
                handler: index.handler                     # your Lambda handler
                runtime: nodejs18.x                        # your Lambda runtime
                role: arn:aws:iam::735902244362:role/lambda_exec_role  # your IAM Role ARN
                
